### ISSUE TITLE
PCB Design

### ISSUE THREAD

**Issue by mikeshams** [ankitpatel9300/Capstone-Project--Summer-2020#10]

**Comment by mikeshams** [comment]
what are the advantages and disadvantages of using different ways for PCB Design?

**Comment by Gurvinder748418** [comment]
PCB designing can be done by using Auto route and Manual route. Manual routing is good for simple and small circuits . while if you want to design complex circuits like PC motherboard. it will be hard to do manually. In easyEDA if we use autoroute disadvantage is that some times its hard to connect or find online server. But there is a other way we can download the offline server (which is called Local Server) to do autoroute. if you don't have the internet. But its only for linux.
