### ISSUE TITLE
COMPONENT TESTING AND CALIBARATION

### ISSUE THREAD

**Issue by mikeshams** [ankitpatel9300/Capstone-Project--Summer-2020#2]

**Comment by mikeshams** [comment]
Please add more details to test the LTE Module.

**Comment by Gurvinder748418** [comment]
[updated Component Testing final.pptx](https://github.com/ankitpatel9300/Capstone-Project--Summer-2020/files/4853975/updated.Component.Testing.final.pptx)

**Comment by mikeshams** [comment]
1. What's the meaning of Calibration?

**Comment by Gurvinder748418** [comment]
It is the process to check whether device is working according to the manufacturer's specification, also we can get desired output of given input of an equipment.Purpose of calibration is to reduce any measurement uncertainty by checking the accuracy of equipment. Main reason for calibration to ensure the reliability of an equipment that it can be trusted.
