### ISSUE TITLE
Interfacing Gas sensor with LPC1769

### ISSUE THREAD

**Issue by krutikafanse** [ankitpatel9300/Capstone-Project--Summer-2020#6]

**Comment by mikeshams** [comment]
1. What issues did you or others might face with connection of the gas sensor to the LPC1769 in terms of Hardware and Software?

**Comment by krutikafanse** [comment]
With Hardware:-  Communication issue can arise. Sensor false triggering can also happen.

With Software:- Improper reading or false detection can happen.

**Comment by krutikafanse** [comment]
Resolved Tx-Rx issue.
Added 1k resistor between LCP1769 and LTE module Tx-Rx connection.
Now connection seems good.
Both Tx and Rx working properly.
