### ISSUE TITLE
FREERTOS CODE DEVELOPMENT

### ISSUE THREAD

**Issue by mikeshams** [ankitpatel9300/Capstone-Project--Summer-2020#9]

**Comment by mikeshams** [comment]
1. Why do we integrate freertos to one project?
2. Can we use freertos for BBB projects? Why?

**Comment by ankitpatel9300** [comment]
Ans.1:- 
          Using FreeRTOS we can enable power saving as it sends CPU in idle mode when no Task is Running.
          Also, FreeRTOS memory management APIs will provide memory optimization in Application. So, we can run the 
          the same application with Low RAM using FreeRTOS.

Ans 2:- Yes We can.
            For Example:- BBB is having two types of CPU.
            1. Cortex A8- Handling Linux OS.
            2. 2xReal-Time CPU for real-time applications.(Cortex- Mx series).
     
           So fundamentally, We can program this Real-time MCU to integrate FreeRTOS.
